export const SET_PAGE = 'SET_PAGE';
export const SET_DEATHS = 'SET_DEATHS';
export const SET_RECOVERED = 'SET_RECOVERED';
export const SET_CONFIRMED = 'SET_CONFIRMED';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_VALUES_TOTAL = 'SET_VALUES_TOTAL';
export const SET_COUNTRIES_INFO_MAY152022 = 'SET_COUNTRIES_INFO_MAY152022';
export const SET_COUNTRIES_INFO_MAY162022 = 'SET_COUNTRIES_INFO_MAY162022';
